# Generated by Django 2.2.16 on 2020-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hhgjhg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hytuyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnbvnbv', models.BigIntegerField()),
            ],
        ),
    ]
